model_name: coco_yolov5

data:
#  train_annotation_path: /home/wangchao/github_resposity/coco/annotations/instances_train2017.json
  train_annotation_path: /home/wangchao/github_resposity/coco/annotations/instances_val2017.json
  val_annotation_path: /home/wangchao/github_resposity/coco/annotations/instances_val2017.json
#  train_img_root: /home/wangchao/github_resposity/coco/images/train2017
  train_img_root: /home/wangchao/github_resposity/coco/images/val2017
  val_img_root: /home/wangchao/github_resposity/coco/images/val2017
  img_size: 640
  batch_size: 8
  num_workers: 8
  debug: False
  remove_blank: Ture


model:
  num_cls: 80
  anchors: [[10, 13, 16, 30, 33, 23],
            [30, 61, 62, 45, 59, 119],
            [116, 90, 156, 198, 373, 326]]
  strides: [8, 16, 32]
  scale_name: s  # s/m/l/x
  freeze_bn: False
  pretrain: ''


hyper_params:
  use_weight_sample: False
  fl_gamma: 0.0
  class_smoothing_eps: 0.0
  anchor_t: 4.0
  iou_type: ciou
  multi_scale: [544,576,608,640,672,704,736]


optim:
  optimizer: SGD
  lr: 0.01
  momentum: 0.937
  milestones: [150, 240]
  cosine_weights: 1.0
  warm_up_epoch: 1.
  weight_decay: 0.0005
  epochs: 300
  sync_bn: True



val:
  interval: 1
  weight_path: weights
  conf_thresh: 0.001
  iou_thresh: 0.6
  max_det: 300


gpus: '0'